config/routes.rb
Rails.application.routes.draw do
  root 'main#index', layout: true

  get '/debug' => 'main#debug'

  # Возвращает css/js файлы, необходимые для отображения форм
  get '/files', to: 'main#files'

  # Возвращает композитную форму с вкладками авторизация/регистрация
  get '/nolayout/auth', to: 'main#auth', layout: false

  # Возвращает информацию о пользователе для buy.vedomosti.ru
  get '/nolayout/buy_profile', to: 'users#buy_profile', layout: false

  # sign up with password
  get  '/sign_up',          to: 'register#sign_up_form', as: :sign_up, layout: true
  get  '/nolayout/sign_up', to: 'register#sign_up_form', layout: false

  post '/sign_up_with_password' => 'register#sign_up_with_password',            layout: true
  post '/nolayout/sign_up_with_password' => 'register#sign_up_with_password',   layout: false

  post '/sign_up_with_oauth'      => 'register#sign_up_with_oauth'
  get  '/auth/:provider/callback' => 'register#oauth_callback', provider: /[a-z0-9_]+/, layout: true
  get  '/auth/failure', to: redirect('/')

  # sign in / out
  get  '/sign_in'  => 'session#sign_in_form',          as: :sign_in,  layout: true
  get  '/nolayout/sign_in'  => 'session#sign_in_form'
  get  '/sign_out' => 'session#sign_out',              as: :sign_out, layout: true
  get  '/nolayout/sign_out' => 'session#sign_out',     layout: false

  # sign in with password
  post '/sign_in_with_password' => 'session#sign_in_with_password'
  post '/nolayout/sign_in_with_password' => 'session#sign_in_with_password', layout: false

  # template only
  get '/blocked_user'            => 'session#blocked_user', layout: true
  get '/nolayout/blocked_user'   => 'session#blocked_user'
  get '/linked_account'          => 'session#linked_account', layout: true
  get '/nolayout/linked_account' => 'session#linked_account'

  # password reset
  get  '/password_reset' => 'register#email_form',  as: :password_reset_email_form, layout: true
  get  '/nolayout/password_reset' => 'register#email_form'

  post '/password_reset' => 'register#check_email', as: :password_reset_email_send, layout: true
  post '/nolayout/password_reset' => 'register#check_email'

  get  '/password_reset/:password_reset_token' => 'register#password_form',   password_reset_token: /[a-z0-9_]+/, as: :password_form, layout: true
  get  '/nolayout/password_reset/:password_reset_token' => 'register#password_form',   password_reset_token: /[a-z0-9_]+/

  post '/password_reset/:password_reset_token' => 'register#password_update', password_reset_token: /[a-z0-9_]+/, as: :password_send, layout: true

  # Профиль пользователя
  get  '/user/profile', to: 'users#show',   as: :users_show,   layout: true
  post '/user/profile', to: 'users#update', as: :users_update, layout: true
  post '/user/phone',   to: 'users#update_phone'
  post '/user/repeat_email_confirm', to: 'users#repeat_email_confirm', as: :users_repeat_email_confirm

  get '/includes/long_cache/user_profile/:access_token' => 'sessions#user_profile', access_token: /[a-f0-9]+/
  get '/confirm' => 'register#confirm'
  get '/social_account_link/:token' => 'register#social_account_link_confirm', token: /[a-f0-9]+/, layout: true

  # Actions для пользователей с мобильной подписки
  scope format: false do
    namespace :mobile do
      get ':operator/new' => 'mobile#new', operator: /mts|beeline|megafon|tele2|wifi/
      resources :wifi, param: :operator, only: %i(new show) do
        collection do
          get ':operator/subscribe'  => 'wifi#subscribe', operator: /mts|beeline|megafon|tele2/
          get :subscribe
        end
      end
      resources :subscribers, only: %i(create new)
      resources :codes, only: %i(new create) do
        collection do
          get :confirm
          post :check
        end
      end
    end
  end
  get '/:operator/wait/:subscription_id', to: 'mobile/pages#wait'

  # contacts
  get  '/subscribe/:slug'          => 'contacts#subscribe_form', slug: /[a-z\d_]+/, layout: true
  get  '/nolayout/subscribe/:slug' => 'contacts#subscribe_form', slug: /[a-z\d_]+/
  post '/subscribe/:slug'          => 'contacts#subscribe', as: :subscribe_send, slug: /[a-z\d_]+/, layout: true
  post '/nolayout/subscribe/:slug' => 'contacts#subscribe', slug: /[a-z\d_]+/

  post '/subscribe_ajax/:slug'     => 'contacts#subscribe_ajax', slug: /[a-z\d_]+/

  get  '/subscribe_confirm/:token' => 'contacts#subscribe_confirm', layout: true
  get  '/unsubscribe/:token'       => 'contacts#unsubscribe', layout: true

  # ниже этого места ничего не трогать!
  get '/*url', to: 'application#not_found'
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :redirect_if_authorized!, only: %i(sign_in_form)
  helper_method :return_url

  def sign_in_form
    if layout?
      @form = :sign_in
      render 'main/index' and return
    end
    @sign_in_form = SignInForm.new
  end

  def sign_in_with_password
    @sign_in_form = SignInForm.new(
        access_token: access_token,
        ip: request.ip,
        **params.fetch(:sign_in_form, {}).symbolize_keys
    )

    use_case = SignInWithPassword.new(@sign_in_form)
    use_case.call

    if use_case.new_token.present?
      response.headers['Set-Cookie'] = token_cookie_header(use_case.new_token)
    end

    if use_case.success?
      unset_cookie(:return_to)
      respond_to do |format|
        format.html { render partial: 'refresh' }
        format.json { render json: use_case.user_data }
      end
    elsif use_case.blocked?
        render nothing: true, status: :unprocessable_entity, :location => blocked_user_url
    else
      respond_to do |format|
        format.html   { render 'session/sign_in_form' }
        format.json   { head :unprocessable_entity }
      end
    end
  end

  def sign_out
    client.delete(
        request.ip,
        '/shark/sign_out',
        access_token: access_token
    )
    redirect_to request.referer || root_url
  end

  def user_profile
    @user = user(params[:access_token]) if params.key?(:access_token)

    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end
end

app/views/session/blocked_user.html.slim
- message = capture
  h5 К сожалению, ваш аккаунт заблокирован
  p Вы были заблокированы, так как не активировали учетную запись. Вам на почту отправлено письмо со ссылкой для активации аккаунта.

= render 'alert', kind: :error, message: message

app/views/session/linked_account.html.slim
- message = capture
  h5 Ваш аккаунт соцсети связан с&nbsp;аккаунтом&nbsp;Ведомостей
  p Ранее вы использовали указанный в аккаунте электронный адрес для регистрации на Ведомостях.
  p На данный адрес отправлено письмо для подтверждения связи аккаунта социальной сети и учетной записи.
  
= render 'alert', kind: :success, message: message

app/views/session/sign_in_form.html.slim
.id-form
  .row

    .col-md-5
      - if !defined?(hide_social_auth)
        = render 'register/oauth_links'

    .col-md-7.dotted
      .wrap
        h5 Вход на сайт
        - render_title('Вход на сайт')

        = form_for @sign_in_form, url: { controller: 'session', action: 'sign_in_with_password', layout: params[:layout] }, html: { 'ng-submit' => 'submit($event)', name: 'form', autocomplete: :off } do |f|

          .field-with-icon
            .icon-holder
              .icons-sprite.icons-login
            = f.text_field :email, placeholder: 'E-mail', 'ng-model' => 'sign_in_form.email', autocomplete: false
            - if @sign_in_form.errors[:email].present?
              .error= @sign_in_form.errors[:email].first

          .field-with-icon
            .icon-holder
              .icons-sprite.icons-lock
            = f.password_field :password, placeholder: 'Пароль', 'ng-model' => 'sign_in_form.password', autocomplete: false
            - if @sign_in_form.errors[:password].present?
              .error= @sign_in_form.errors[:password].first

          =
          = link_to 'Забыли пароль?', "#{Settings.hosts.lago}#{password_reset_email_form_path}", class: 'underline'

          button{type='submit'} Войти

app/views/session/subscribe_form.html.slim
.id-form
  .row

    .col-md-5
      - if !defined?(hide_social_auth)
        = render 'register/oauth_links'

    .col-md-7.dotted
      .wrap
        h5 Вход на сайт
        - render_title('Вход на сайт')

        = form_for @sign_in_form, url: { controller: 'session', action: 'sign_in_with_password', layout: params[:layout] }, html: { 'ng-submit' => 'submit($event)', name: 'form', autocomplete: :off } do |f|

          .field-with-icon
            .icon-holder
              .icons-sprite.icons-login
            = f.text_field :email, placeholder: 'E-mail', 'ng-model' => 'sign_in_form.email', autocomplete: false
            - if @sign_in_form.errors[:email].present?
              .error= @sign_in_form.errors[:email].first

          .field-with-icon
            .icon-holder
              .icons-sprite.icons-lock
            = f.password_field :password, placeholder: 'Пароль', 'ng-model' => 'sign_in_form.password', autocomplete: false
            - if @sign_in_form.errors[:password].present?
              .error= @sign_in_form.errors[:password].first

          =
          = link_to 'Забыли пароль?', "#{Settings.hosts.lago}#{password_reset_email_form_path}", class: 'underline'

          button{type='submit'} Войти

app/views/session/success_login.html.slim
.id-alert{class="id-alert_success"}
  h5 Вы успешно вошли на сайт.

app/views/session/too_many_sessions.html.slim
- message = capture
  h5 Слишком много открытых сессий.

= render 'alert', kind: :error, message: message