config/routes.rb
Rails.application.routes.draw do
  root 'main#index', layout: true

  get '/debug' => 'main#debug'

  # Возвращает css/js файлы, необходимые для отображения форм
  get '/files', to: 'main#files'

  # Возвращает композитную форму с вкладками авторизация/регистрация
  get '/nolayout/auth', to: 'main#auth', layout: false

  # Возвращает информацию о пользователе для buy.vedomosti.ru
  get '/nolayout/buy_profile', to: 'users#buy_profile', layout: false

  # sign up with password
  get  '/sign_up',          to: 'register#sign_up_form', as: :sign_up, layout: true
  get  '/nolayout/sign_up', to: 'register#sign_up_form', layout: false

  post '/sign_up_with_password' => 'register#sign_up_with_password',            layout: true
  post '/nolayout/sign_up_with_password' => 'register#sign_up_with_password',   layout: false

  post '/sign_up_with_oauth'      => 'register#sign_up_with_oauth'
  get  '/auth/:provider/callback' => 'register#oauth_callback', provider: /[a-z0-9_]+/, layout: true
  get  '/auth/failure', to: redirect('/')

  # sign in / out
  get  '/sign_in'  => 'session#sign_in_form',          as: :sign_in,  layout: true
  get  '/nolayout/sign_in'  => 'session#sign_in_form'
  get  '/sign_out' => 'session#sign_out',              as: :sign_out, layout: true
  get  '/nolayout/sign_out' => 'session#sign_out',     layout: false

  # sign in with password
  post '/sign_in_with_password' => 'session#sign_in_with_password'
  post '/nolayout/sign_in_with_password' => 'session#sign_in_with_password', layout: false

  # template only
  get '/blocked_user'            => 'session#blocked_user', layout: true
  get '/nolayout/blocked_user'   => 'session#blocked_user'
  get '/linked_account'          => 'session#linked_account', layout: true
  get '/nolayout/linked_account' => 'session#linked_account'

  # password reset
  get  '/password_reset' => 'register#email_form',  as: :password_reset_email_form, layout: true
  get  '/nolayout/password_reset' => 'register#email_form'

  post '/password_reset' => 'register#check_email', as: :password_reset_email_send, layout: true
  post '/nolayout/password_reset' => 'register#check_email'

  get  '/password_reset/:password_reset_token' => 'register#password_form',   password_reset_token: /[a-z0-9_]+/, as: :password_form, layout: true
  get  '/nolayout/password_reset/:password_reset_token' => 'register#password_form',   password_reset_token: /[a-z0-9_]+/

  post '/password_reset/:password_reset_token' => 'register#password_update', password_reset_token: /[a-z0-9_]+/, as: :password_send, layout: true

  # Профиль пользователя
  get  '/user/profile', to: 'users#show',   as: :users_show,   layout: true
  post '/user/profile', to: 'users#update', as: :users_update, layout: true
  post '/user/phone',   to: 'users#update_phone'
  post '/user/repeat_email_confirm', to: 'users#repeat_email_confirm', as: :users_repeat_email_confirm

  get '/includes/long_cache/user_profile/:access_token' => 'sessions#user_profile', access_token: /[a-f0-9]+/
  get '/confirm' => 'register#confirm'
  get '/social_account_link/:token' => 'register#social_account_link_confirm', token: /[a-f0-9]+/, layout: true

  # Actions для пользователей с мобильной подписки
  scope format: false do
    namespace :mobile do
      get ':operator/new' => 'mobile#new', operator: /mts|beeline|megafon|tele2|wifi/
      resources :wifi, param: :operator, only: %i(new show) do
        collection do
          get ':operator/subscribe'  => 'wifi#subscribe', operator: /mts|beeline|megafon|tele2/
          get :subscribe
        end
      end
      resources :subscribers, only: %i(create new)
      resources :codes, only: %i(new create) do
        collection do
          get :confirm
          post :check
        end
      end
    end
  end
  get '/:operator/wait/:subscription_id', to: 'mobile/pages#wait'

  # contacts
  get  '/subscribe/:slug'          => 'contacts#subscribe_form', slug: /[a-z\d_]+/, layout: true
  get  '/nolayout/subscribe/:slug' => 'contacts#subscribe_form', slug: /[a-z\d_]+/
  post '/subscribe/:slug'          => 'contacts#subscribe', as: :subscribe_send, slug: /[a-z\d_]+/, layout: true
  post '/nolayout/subscribe/:slug' => 'contacts#subscribe', slug: /[a-z\d_]+/

  post '/subscribe_ajax/:slug'     => 'contacts#subscribe_ajax', slug: /[a-z\d_]+/

  get  '/subscribe_confirm/:token' => 'contacts#subscribe_confirm', layout: true
  get  '/unsubscribe/:token'       => 'contacts#unsubscribe', layout: true

  # ниже этого места ничего не трогать!
  get '/*url', to: 'application#not_found'
end

app/models/user.rb
class User
  include ActiveModel::Model
  
  attr_accessor :id, :status, :avatar, :birthday, :address
  attr_accessor :company_speciality_id, :appointment_id, :income_id, :auto_id
  attr_accessor :access_token, :access_rights, :autopay, :created_at, :sub_end_date, :renewal_date
  
  attr_accessor :ip, :mail_types
  
  validates_presence_of :first_name, :last_name, :email
  validates_acceptance_of :rules, message: 'надо согласиться'
  
  %i(first_name last_name phone email nickname company).each do |attribute|
    attr_reader attribute
    
    define_method("#{attribute}=") do |value|
      instance_variable_set("@#{attribute}", value.to_s.strip)
    end
  end
  
  def attributes
    {
      first_name:   first_name,
      last_name:    last_name,
      email:        email,
      phone:        phone,
      nickname:     nickname,
      access_token: access_token, 
      mail_types:   mail_types
    }
  end
  
  def access_rights
    @access_rights.map { |ar| AccessRight.new(ar) }
  end
  
  def save
    if valid?
      response = self.class.client.post(ip, self.class.sign_up_url, user: attributes)
      
      if response.success?
        true
      else
        @aquarium_errors = response.body
        false
      end
    end
  end
  
  def error_messages
    if valid?
      @aquarium_errors
    else
      errors.messages
    end
  end
  
  def avatar_url
    if avatar.present? && avatar.key?(:versions) && avatar[:versions].key?(:original)
      "http://#{Settings.hosts.agami}#{avatar[:versions][:original][:url]}"
    end
  end
  
  # for hypercomments
  def for_auth_hash
    {
      nick:        nickname,
      avatar:      avatar_url,
      id:          id.to_s,
      email:       email,
      profile_url: "#{Settings.hosts.shark}/user/profile"
    }
  end
  
  # for hypercomments
  def auth_hash
    timestamp   = Time.now().to_i
    user_base64 = Base64.encode64(for_auth_hash.to_json.to_s).split.join
    digest      = Digest::MD5.hexdigest("#{Settings.hypercomments.secret_key}#{user_base64}#{timestamp}")
    "#{user_base64}_#{timestamp}_#{digest}" if status=='subscriber'
  end
  
  # for falco
  def for_user_options
    {
      id:            id,
      status:        status,
      auth_provider: provider,
      created_at:    created_at
    }.to_json
  end

  def for_mailing
    {
      mail_types: mail_types
    }.to_json
  end
  
  def provider
    response = self.class.client.get(ip, "/shark/sessions/#{access_token}")
    if response.success?
      response.body[:account_type]
    end
  end
  
  class << self
    attr_reader :options
    
    def sign_up_url
      raise NotImplementedError
    end
    
    def client
      @client ||= AquariumClient.new
    end
    
    def confirm(token, ip)
      client.post(ip, '/shark/confirm', token: token).success?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_current_user

  def show
    if @user_data = user_profile(access_token)
      @form = ProfileForm.new(access_token: access_token, **@user_data)
      @password_updated = params[:password_updated]
      @access_rights = access_rights_data(@form.access_rights)
      
      respond_to do |format|
        format.html
        format.json { render json: { user: @user_data, access_rights: @access_rights } }
      end
    else
      redirect_to root_url
    end
  end

  def update
    if @user_data = user_profile(access_token)
      profile_form = params[:profile_form].symbolize_keys
      @form = ProfileForm.new(ip: request.ip, access_token: access_token, **profile_form)
      if @form.save
        # страшный костыль, спасибо проектантам
        # сохраняем всю форму, а нужно поймать только признак сохранения пароля
        if profile_form[:password].present?
          redirect_to users_show_path(password_updated: true)
        else
          redirect_to users_show_path
        end
      else
        # если обнаружили ошибку заменим mail_types на нормальные объекты (а то там остаются введенный массив id-шников)
        # TODO: По хорошему их надо развести по разным переменным
        @user_data[:mail_types].each { |t| t[:checked] = Array(profile_form[:mail_types]).include?(t[:id].to_s) ? true : false }
        @form = ProfileForm.new(ip: request.ip, access_token: access_token, **profile_form.merge(mail_types: @user_data[:mail_types]))
        render :show
      end
    else
      redirect_to root_url
    end
  end

  def update_phone
    use_case = UpdateUserPhone.new(request.ip, access_token, params[:phone])
    use_case.call
    
    if use_case.success?
      head :ok
    else
      head :unprocessable_entity
    end
  end
  
  def repeat_email_confirm
    use_case = RepeatEmailConfirm.new(access_token, request.ip)
    use_case.call
    
    if use_case.success?
      head :ok
    else
      head :unprocessable_entity
    end
  end

  # возвращает юзера для buy.vedomosti.ru
  def buy_profile
    @user = user_profile(access_token)
    @form = ProfileForm.new(ip: request.ip, access_token: access_token)

    respond_to do |format|
      format.html
      format.json { render json: { user: @user, form: @form, access_rights: @access_rights } }
    end
  end


private
  def user_profile(access_token)
    response = client.get(request.ip, "/shark/users/#{access_token}/profile", {}, access_token)
    response.body if response.success?
  end

  def set_current_user
    @current_user = user(access_token)
  end

  def access_rights_data(access_rights)
    access_rights.map do |access_right|
      data = nil
      
      if access_right.start_date.present? && access_right.end_date.present?
        data = {
          start_date: I18n.l(Time.parse(access_right.start_date), format: :date_only),
          end_date:   I18n.l(Time.parse(access_right.end_date), format: :date_only)
        }
        
        data[:price]   = access_right.price
        data[:product] = access_right.subproduct_title
        data[:period]  = access_right.subproduct_period
        data[:payment_id]  = access_right.payment_id
        data[:paymethod] = access_right.paymethod
        data
      end
    end.compact
  end
end

app/views/users/buy_profile.html.slim
- if @user
  .b-user{ng-init="initUser('#{@user[:first_name]}', '#{@user[:last_name]}', '#{@user[:phone]}', '#{@user[:email]}')"}
    .b-user__inner
      .b-user__text
        span.icons-sprite.icons-portrait
        span.name
          | {{user.first_name}} {{user.last_name}}

      form.b-user__exit{action="#{Settings.hosts.lago}/sign_out"}
        button{type='submit'}
          span.text
            | Выйти

app/views/users/show.html.slim
- render_title 'Профиль пользователя'
- if @user_data[:status] == 'registered'
  id-repeat-letter
    .b-message
      p.b-message_error{ng-show="isSended == 0"}
        | Ваш аккаунт не подтвержден. Перейдите по ссылке из письма, которое мы отправили вам при регистрации. Если вы не можете найти это письмо, то проверьте e-mail, указанный вами в личном кабинете, и воспользуйтесь кнопкой «Отправить повторно»
      p.b-message_error{ng-show="isSended == 1"}
        | Письмо со ссылкой для подтверждения аккаунта отправлено на ваш e-mail.
      p.b-message_error{ng-show="isSended == 2"}
        | Вы уже отправляли письмо и подтвердили аккаунт.
      button.b-button.b-button_error{ng-show="isSended == 0" ng-click="sendLetter($event)"} Отправить повторно

.id-form.id-profile{id-profile-form}
  .row
    .col-md-12
      - if !(@access_rights.present? && has_active_subscription(@access_rights))
        .b-subscription-warning
          .b-subscription-warning__text = 'У вас нет активной подписки'
          .b-subscription-warning__button
            a.b-button.b-button--subscribe {href="#{Settings.hosts.metynnis}"} = 'Оформить подписку'
      = form_for @form, url: users_update_path do |f|
        h5 Профиль

        .section
          .left
            .wrap
              = f.label :first_name, 'Имя'
              = f.text_field :first_name
              - if @form.errors[:first_name].present?
                .error= @form.errors[:first_name].first

              = f.label :email, 'E-mail'
              = f.text_field :email
              - if @form.errors[:email].present?
                .error= @form.errors[:email].first

          .right
            .wrap
              = f.label :last_name, 'Фамилия'
              = f.text_field :last_name
              - if @form.errors[:last_name].present?
                .error= @form.errors[:last_name].first

              = f.label :phone, 'Телефон'
              = f.text_field :phone, 'mask' => '+9 (999) 999-99-99', 'ng-init' => "profile.phone='#{@form.phone}'",'ng-model' => 'profile.phone', 'mask-restrict' => 'reject'
              - if @form.errors[:phone].present?
                .error= @form.errors[:phone].first

        h5.margin Сменить пароль

        .section

          .left
            .wrap
              = f.label :password, 'Новый пароль'
              = f.password_field :password
              - if @form.errors[:password].present?
                .error= @form.errors[:password].first

          .right
            .wrap
              = f.label :password_confirmation, 'Подтверждение'
              = f.password_field :password_confirmation
              - unless @form.valid?
                .error= @form.errors[:password_confirmation].first

        - if @user_data[:status] == 'confirmed'
          h5.margin Рассылка

          .section
            - @form.mail_types.each do |mail_type|
              .checkbox2
                = f.check_box :mail_types, {multiple: true, 'ng-checked' => mail_type[:checked], 'checklist-model' => 'profile.mail_types', 'checklist-value' => mail_type[:id]}, mail_type[:id], nil
                = f.label "mail_types_#{mail_type[:id]}", {style: ''}
                  | Получать ежедневную рассылку «#{mail_type[:title]}»

            .actions
              button{type='submit'} Сохранить
              - if @password_updated
                span.message Ваш пароль изменён
              - if @mail_types_updated
                span.message Ваш список рассылок обновлен

        - if @access_rights.present?
          /- active = active_subscription(@access_rights)
          - if has_active_subscription(@access_rights)


            .subscriptions
              h5.line Активная подписка
              input {name="profile_form[autopay]" id="activeVal" type="hidden" value="#{@user_data[:autopay]}"}
              .section.mobile-hide {class="#{has_active_subscription(@access_rights) ? 'section--no-margin' : ''}"}
                .row
                  .col-md-12.table-reflow
                    table.table.cf
                      thead.cf
                        tr
                          th №
                          th Начало
                          th Окончание
                          th Стоимость, руб
                          th Способ оплаты
                          th Продукт
                      tbody
                        - @access_rights.each do |access_right|
                          - if Time.parse(access_right[:end_date]) > Time.now && access_right[:paymethod]
                            tr {class="#{Time.parse(access_right[:end_date]) > Time.now && access_right[:paymethod] && access_right[:paymethod][:slug] == 'card' ? 'active' : ''}"}
                              th = access_right[:payment_id] || raw('&nbsp;')
                              td = access_right[:start_date]|| raw('&nbsp;')
                              td = access_right[:end_date]|| raw('&nbsp;')
                              td = access_right[:price]|| raw('&nbsp;')
                              td = access_right[:paymethod] && access_right[:paymethod][:title] || raw('&nbsp;')
                              td  #{access_right[:product]} (#{access_right[:period]})

              .section.mobile-show
                .row
                  .col-md-12{ng-init='shown=0'}
                    - @access_rights.each_with_index do |access_right, i|
                      - if Time.parse(access_right[:end_date]) > Time.now && access_right[:paymethod]
                        .b-subscription
                          .b-accordion
                            .b-accordion__head
                              .b-sub-row
                                .b-sub-row__cell = "Заказ №#{access_right[:payment_id]}"
                                .b-sub-row__cell
                                  span.icons-sprite.icons-plus-circle {ng-show="shown!=#{i}" ng-click='shown=#{i}'}
                                  span.icons-sprite.icons-minus-circle {ng-show="shown==#{i}" ng-click='shown=-1'}
                            .b-accordion__body {ng-show="shown==#{i}"}
                              .b-sub-row
                                .b-sub-row__cell = 'Начало'
                                .b-sub-row__cell = access_right[:start_date]|| raw('&nbsp;')
                              .b-sub-row
                                .b-sub-row__cell = 'Окончание'
                                .b-sub-row__cell = access_right[:end_date]|| raw('&nbsp;')
                              .b-sub-row
                                .b-sub-row__cell = 'Стоимость, руб'
                                .b-sub-row__cell = access_right[:price]|| raw('&nbsp;')
                              .b-sub-row
                                .b-sub-row__cell = 'Способ оплаты'
                                .b-sub-row__cell = access_right[:paymethod] && access_right[:paymethod][:title] || raw('&nbsp;')
                              .b-sub-row
                                .b-sub-row__cell = 'Продукт'
                                .b-sub-row__cell = access_right[:product]|| raw('&nbsp;')
                                /&& access_right[:paymethod][:slug] == 'card'
          - if @user_data[:next_billing] && @user_data[:autopay]
            .subscriptions
              h5.line.line-autopay Автоплатеж
              .autopay
                .checkbox2
                  input {type='checkbox' id='enabled' ng-model="profile.enabled" ng-init="profile.enabled = #{@user_data[:autopay]}" class='green' ng-change='messageShown=true'}
                  label = "Услуга включает \"Автоплатеж\". #{Time.parse(@user_data[:next_billing][:date]).strftime('%d.%m.%Y')} c вашей банковской карты автоматически спишется #{@user_data[:next_billing][:summ].to_i} рублей за оплату подписки на следующий период."


          - if @access_rights.any? {|access_right| !(Time.parse(access_right[:end_date]) > Time.now && access_right[:paymethod]) }
            .subscriptions
              h5.line История покупок
              .section.mobile-hide {class="#{has_active_subscription(@access_rights) ? 'section--no-margin' : ''}"}
                .row
                  .col-md-12.table-reflow
                    table.table.cf
                      thead.cf
                        tr
                          th №
                          th Начало
                          th Окончание
                          th Стоимость, руб
                          th Способ оплаты
                          th Продукт

                      tbody
                        - @access_rights.each do |access_right|
                          - if !(Time.parse(access_right[:end_date]) > Time.now && access_right[:paymethod])
                            tr {class="#{Time.parse(access_right[:end_date]) > Time.now && access_right[:paymethod] && access_right[:paymethod][:slug] == 'card' ? 'active' : ''}"}
                              th = access_right[:payment_id] || raw('&nbsp;')
                              td = access_right[:start_date]|| raw('&nbsp;')
                              td = access_right[:end_date]|| raw('&nbsp;')
                              td = access_right[:price]|| raw('&nbsp;')
                              td = access_right[:paymethod] && access_right[:paymethod][:title] || raw('&nbsp;')
                              td  #{access_right[:product]} (#{access_right[:period]})

                    .hint По всем вопросам связанным с подпиской обращайтесь: +7 (495) 232 17 53, <a href="mailto:podpiska@vedomosti.ru">podpiska@vedomosti.ru</a>
              .section.mobile-show
                .row
                  .col-md-12
                    - @access_rights.each_with_index do |access_right, i|
                      - if !(Time.parse(access_right[:end_date]) > Time.now && access_right[:paymethod])
                        .b-subscription
                          .b-accordion
                            .b-accordion__head
                              .b-sub-row
                                .b-sub-row__cell = "Заказ №#{access_right[:payment_id]}"
                                .b-sub-row__cell
                                  span.icons-sprite.icons-plus-circle {ng-show="shown!=#{i}" ng-click='shown=#{i}'}
                                  span.icons-sprite.icons-minus-circle {ng-show="shown==#{i}" ng-click='shown=-1'}
                            .b-accordion__body {ng-show="shown==#{i}"}
                              .b-sub-row
                                .b-sub-row__cell = 'Начало'
                                .b-sub-row__cell = access_right[:start_date]|| raw('&nbsp;')
                              .b-sub-row
                                .b-sub-row__cell = 'Окончание'
                                .b-sub-row__cell = access_right[:end_date]|| raw('&nbsp;')
                              .b-sub-row
                                .b-sub-row__cell = 'Стоимость, руб'
                                .b-sub-row__cell = access_right[:price]|| raw('&nbsp;')
                              .b-sub-row
                                .b-sub-row__cell = 'Способ оплаты'
                                .b-sub-row__cell = access_right[:paymethod] && access_right[:paymethod][:title] || raw('&nbsp;')
                              .b-sub-row
                                .b-sub-row__cell = 'Продукт'
                                .b-sub-row__cell = access_right[:product]|| raw('&nbsp;')

                .hint По всем вопросам связанным с подпиской обращайтесь: +7 (495) 232 17 53, <a href="mailto:podpiska@vedomosti.ru">podpiska@vedomosti.ru</a>
      .b-logout
        a.b-button.b-button--logout {href='/sign_out/'} = 'Выйти из аккаунта'
  .b-message-wrapper.ng-cloak {ng-show='messageShown'}

    .b-message
      .b-message__close {ng-click='messageShown = false; profile.enabled=!profile.enabled' ng-show='!processing'}
        span.icons-sprite.icons-exit-tan
      .b-message__title
        | Внимание!
      .b-message__text = 'Вы отключаете автоматическое продление подписки на "Ведомости". Вернуть автоплатеж вы сможете при следующем заказе.'
      .b-message__button {ng-show='!processing'}
        button.b-button { ng-click='accept()'} = 'Отключить'
      a.b-message__close-link {ng-click='messageShown = false; profile.enabled=!profile.enabled'} = 'Сохранить автопродление'