config/routes.rb
Rails.application.routes.draw do
  root 'main#index', layout: true

  get '/debug' => 'main#debug'

  # Возвращает css/js файлы, необходимые для отображения форм
  get '/files', to: 'main#files'

  # Возвращает композитную форму с вкладками авторизация/регистрация
  get '/nolayout/auth', to: 'main#auth', layout: false

  # Возвращает информацию о пользователе для buy.vedomosti.ru
  get '/nolayout/buy_profile', to: 'users#buy_profile', layout: false

  # sign up with password
  get  '/sign_up',          to: 'register#sign_up_form', as: :sign_up, layout: true
  get  '/nolayout/sign_up', to: 'register#sign_up_form', layout: false

  post '/sign_up_with_password' => 'register#sign_up_with_password',            layout: true
  post '/nolayout/sign_up_with_password' => 'register#sign_up_with_password',   layout: false

  post '/sign_up_with_oauth'      => 'register#sign_up_with_oauth'
  get  '/auth/:provider/callback' => 'register#oauth_callback', provider: /[a-z0-9_]+/, layout: true
  get  '/auth/failure', to: redirect('/')

  # sign in / out
  get  '/sign_in'  => 'session#sign_in_form',          as: :sign_in,  layout: true
  get  '/nolayout/sign_in'  => 'session#sign_in_form'
  get  '/sign_out' => 'session#sign_out',              as: :sign_out, layout: true
  get  '/nolayout/sign_out' => 'session#sign_out',     layout: false

  # sign in with password
  post '/sign_in_with_password' => 'session#sign_in_with_password'
  post '/nolayout/sign_in_with_password' => 'session#sign_in_with_password', layout: false

  # template only
  get '/blocked_user'            => 'session#blocked_user', layout: true
  get '/nolayout/blocked_user'   => 'session#blocked_user'
  get '/linked_account'          => 'session#linked_account', layout: true
  get '/nolayout/linked_account' => 'session#linked_account'

  # password reset
  get  '/password_reset' => 'register#email_form',  as: :password_reset_email_form, layout: true
  get  '/nolayout/password_reset' => 'register#email_form'

  post '/password_reset' => 'register#check_email', as: :password_reset_email_send, layout: true
  post '/nolayout/password_reset' => 'register#check_email'

  get  '/password_reset/:password_reset_token' => 'register#password_form',   password_reset_token: /[a-z0-9_]+/, as: :password_form, layout: true
  get  '/nolayout/password_reset/:password_reset_token' => 'register#password_form',   password_reset_token: /[a-z0-9_]+/

  post '/password_reset/:password_reset_token' => 'register#password_update', password_reset_token: /[a-z0-9_]+/, as: :password_send, layout: true

  # Профиль пользователя
  get  '/user/profile', to: 'users#show',   as: :users_show,   layout: true
  post '/user/profile', to: 'users#update', as: :users_update, layout: true
  post '/user/phone',   to: 'users#update_phone'
  post '/user/repeat_email_confirm', to: 'users#repeat_email_confirm', as: :users_repeat_email_confirm

  get '/includes/long_cache/user_profile/:access_token' => 'sessions#user_profile', access_token: /[a-f0-9]+/
  get '/confirm' => 'register#confirm'
  get '/social_account_link/:token' => 'register#social_account_link_confirm', token: /[a-f0-9]+/, layout: true

  # Actions для пользователей с мобильной подписки
  scope format: false do
    namespace :mobile do
      get ':operator/new' => 'mobile#new', operator: /mts|beeline|megafon|tele2|wifi/
      resources :wifi, param: :operator, only: %i(new show) do
        collection do
          get ':operator/subscribe'  => 'wifi#subscribe', operator: /mts|beeline|megafon|tele2/
          get :subscribe
        end
      end
      resources :subscribers, only: %i(create new)
      resources :codes, only: %i(new create) do
        collection do
          get :confirm
          post :check
        end
      end
    end
  end
  get '/:operator/wait/:subscription_id', to: 'mobile/pages#wait'

  # contacts
  get  '/subscribe/:slug'          => 'contacts#subscribe_form', slug: /[a-z\d_]+/, layout: true
  get  '/nolayout/subscribe/:slug' => 'contacts#subscribe_form', slug: /[a-z\d_]+/
  post '/subscribe/:slug'          => 'contacts#subscribe', as: :subscribe_send, slug: /[a-z\d_]+/, layout: true
  post '/nolayout/subscribe/:slug' => 'contacts#subscribe', slug: /[a-z\d_]+/

  post '/subscribe_ajax/:slug'     => 'contacts#subscribe_ajax', slug: /[a-z\d_]+/

  get  '/subscribe_confirm/:token' => 'contacts#subscribe_confirm', layout: true
  get  '/unsubscribe/:token'       => 'contacts#unsubscribe', layout: true

  # ниже этого места ничего не трогать!
  get '/*url', to: 'application#not_found'
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  before_action :redirect_if_authorized!, only: %i(sign_up_form)
  helper_method :return_url

  def sign_up_form
    if layout?
      @form = :sign_up
      render 'main/index' and return
    end
    @registration_form = PasswordRegistrationForm.new
  end

  def sign_up_with_password
    @registration_form = PasswordRegistrationForm.new(
      access_token: access_token,
      ip: request.ip,
      **params.fetch(:password_registration_form, {}).symbolize_keys
    )

    use_case = SignUpWithPassword.new(@registration_form)
    use_case.call

    if use_case.new_token.present?
      response.headers['Set-Cookie'] = token_cookie_header(use_case.new_token)
    end

    if use_case.success?
      respond_to do |format|

        # Для внедрённых форм делаем редирект через js, для остальных — обычный редирект.
        response.headers['registered'] = 'true'
        format.html { layout? ? redirect_to('/user/profile') : render(partial: 'refresh') }
        format.json { render json: use_case.user_data }
      end
    else
      response.headers['registered'] = 'false'
      respond_to do |format|
        format.html { render 'register/sign_up_form' }
        format.json { render json: @registration_form.errors, status: :unprocessable_entity }
      end
    end
  end

  def oauth_callback
    @form = OauthRegistrationForm.from_auth_hash(
      auth_hash,
      ip: request.ip,
      access_token: access_token
    )

    use_case = SignInWithOauth.new(@form)
    use_case.call

    if use_case.new_token.present?
      response.headers['Set-Cookie'] = token_cookie_header(use_case.new_token)
    end

    if use_case.success?
      delete_cookie_and_redirect
    elsif use_case.linked?
      redirect_to linked_account_url
    elsif use_case.blocked?
      redirect_to blocked_user_url
    else
      respond_to do |format|
        format.html
      end
    end
  end

  def sign_up_with_oauth
    @form = OauthRegistrationForm.new(
      access_token: access_token,
      ip: request.ip,
      **params[:oauth_registration_form].symbolize_keys
    )

    use_case = SignUpWithOauth.new(@form)
    use_case.call

    if use_case.success?
      delete_cookie_and_redirect
    else
      respond_to do |format|
        format.html { render 'register/oauth_callback' }
      end
    end
  end

  def oauth_failure
    render text: 'failure'
  end

  def email_form
    @email_form = EmailForm.new
  end

  def check_email
    @email_form = EmailForm.new(params[:email_form])

    if @email_form.valid?
      use_case = SendPasswordResetEmail.new(params[:email_form][:email], request.ip)
      use_case.call
      @success = use_case.success?
      @email_form.errors.add(:email, :not_found) unless @success
    end

    render 'register/email_form'
  end

  def password_form
    use_case = CheckPasswordResetToken.new(params[:password_reset_token], request.ip)
    use_case.call

    @password_form = PasswordForm.new
    @check_token_success = use_case.success?
  end

  def password_update
    @check_token_success = true

    @password_form = PasswordForm.new(params[:password_form])

    if @password_form.valid?
      use_case = ResetPassword.new(
        params[:password_form][:password],
        params[:password_reset_token],
        access_token,
        request.ip
      )
      use_case.call

      @success = use_case.success?
      @password_form.errors.add(:password, :unknown_error) unless @success
    end

    render 'register/password_form'
  end

  def confirm
    if User.confirm(params[:token], request.ip)
      delete_cookie_and_redirect #, notice: 'ok'
    else
      redirect_to users_show_url, notice: 'fail'
    end
  end

  def social_account_link_confirm
    use_case = SocialAccountLinkConfirm.new(params[:token], access_token, request.ip)
    use_case.call

    if @success = use_case.success?
      render 'social_account_link_success'
    else
      render 'social_account_link_failed'
    end
  end

private
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/views/register/_header.html.slim
.title
  |Регистрация
.subtitle
  |Добро пожаловать в Сообщество читателей «Ведомостей».

.descr
p
  |После регистрации вы сможете читать до 13 материалов vedomosti.ru в месяц. Если хотите читать больше, оформите подписку.
  br
  | Мы рекомендуем регистрироваться под настоящим именем и оставляем за собой право удалять некорректную информацию.
  br
  | АО «Бизнес Ньюс Медиа» обязуется использовать персональные данные своих пользователей в соответствии с Правилами регистрации и конфиденциальности.

app/views/register/_oauth_form.html.slim
.id-form{id-oauth-form}
  .row

    .col-md-5
      h5 Регистрация

      .hint
        | Уважаемый читатель, чтобы войти на <a href="http://vedomosti.ru">vedomosti.ru</a>, заполните недостающие поля своего профиля. Пожалуйста, укажите свои настоящие имя и фамилию.

    .col-md-7.dotted
      .wrap
        h5 &nbsp;

        = form_for(@form, url: { controller: 'register', action: 'sign_up_with_oauth', layout: params[:layout] },  html: { name: 'oauth_form' }) do |f|
          = f.text_field :email, placeholder: 'Email *'
          - if @form.errors[:email].present?
            .error= @form.errors[:email].first

          = f.text_field :last_name, placeholder: 'Фамилия *'
          - if @form.errors[:last_name].present?
            .error= @form.errors[:last_name].first

          = f.text_field :first_name, placeholder: 'Имя *'
          - if @form.errors[:first_name].present?
            .error= @form.errors[:first_name].first

          = f.text_field :phone, placeholder: 'Телефон', 'mask' => '+9 (999) 999-99-99', 'ng-init' => "oauth_form.phone ='#{@form.phone}'", 'ng-model' => 'oauth_form.phone'
          - if @form.errors[:phone].present?
            .error= @form.errors[:phone].first

          / .checkbox
          /   = f.check_box :mailing_type_slugs, {multiple: true, 'checklist-model' => 'oauth_form.mailing_type_slugs'}, "newsrelease", nil
          /   = label :password_registration_form, style: 'display: inline'
          /     | Я хочу получать ежедневную рассылку «Свежий номер «Ведомостей»

          .checkbox
            = f.check_box :rules, 'ng-model' => 'rules'
            = label :oauth_registration_form, :rules, style: 'display: inline'
              | Я согласен с правилами 
              = link_to 'регистрации и конфиденциальности', '//www.vedomosti.ru/info/privacy'

          button{type='submit' ng-disabled='!rules'} Сохранить

app/views/register/_oauth_links.html.slim
.id-socials
  h5 Быстрый вход
  a.btn.icons-sprite.icons-fb{href="#{Settings.hosts.lago}/auth/facebook"}
  a.btn.icons-sprite.icons-tw{href="#{Settings.hosts.lago}/auth/twitter"}
  a.btn.icons-sprite.icons-vk{href="#{Settings.hosts.lago}/auth/vkontakte"}

app/views/register/_password_form.html.slim
= form_for(@registration_form, url: { controller: 'register', action: 'sign_up_with_password', layout: params[:layout] }, html: { form: :form, 'ng-submit' => 'submit($event)' }) do |f|

  = f.text_field :email, placeholder: 'E-mail *', 'ng-init' => "password_registration_form.email = '#{@registration_form.email}'", 'ng-model' => 'password_registration_form.email', 'ng-change' => 'inputStarted("password_registration_form_email")'
  - if @registration_form.errors[:email].present?
    .error= @registration_form.errors[:email].first
  .password-field {password-field='register-reveal'}
    = f.password_field :password, placeholder: 'Пароль *', 'ng-init' => "password_registration_form.password = '#{@registration_form.password}'", 'ng-model' => 'password_registration_form.password', 'ng-change' => 'inputStarted("password_registration_form_password")'
    - if @registration_form.errors[:password].present?
      .error{ng-hide='touched'}= @registration_form.errors[:password].first
    #register-reveal.password-field__reveal
  = f.text_field :last_name, placeholder: 'Фамилия *', 'ng-init' => "password_registration_form.last_name = '#{@registration_form.last_name}'", 'ng-model' => 'password_registration_form.last_name', 'ng-change' => 'inputStarted("password_registration_form_email")'
  - if @registration_form.errors[:last_name].present?
    .error= @registration_form.errors[:last_name].first
  = f.text_field :first_name, placeholder: 'Имя *', 'ng-init' => "password_registration_form.first_name = '#{@registration_form.first_name}'", 'ng-model' => 'password_registration_form.first_name', 'ng-change' => 'inputStarted("password_registration_form_first_name")'
  - if @registration_form.errors[:first_name].present?
    .error{ng-hide='touched'}= @registration_form.errors[:first_name].first

  = f.text_field :phone, placeholder: 'Телефон', 'ng-init' => "password_registration_form.phone = '#{@registration_form.phone}'", 'ng-model' => 'password_registration_form.phone', 'mask' => '+9 (999) 999-99-99', 'mask-restrict' => 'reject', 'ng-change' => 'inputStarted("password_registration_form_phone")'
  - if @registration_form.errors[:phone].present?
    .error{ng-hide='touched'}= @registration_form.errors[:phone].first

  .checkbox
    = f.check_box :mailing_type_slugs, {multiple: true, 'checklist-model' => 'password_registration_form.mailing_type_slugs'}, "newsrelease", nil
    = label :password_registration_form, :mailing_type_slugs_newsrelease, style: 'display: inline'
      | Я хочу получать ежедневную рассылку «Свежий номер «Ведомостей»

  .checkbox{ng-init='rules=true'}
    = f.check_box :rules, 'ng-model' => 'rules'
    = label :password_registration_form, :rules, style: 'display: inline'
      = 'Нажимая кнопку «Зарегистрироваться», я подтверждаю, что ознакомился и принимаю '
      = link_to 'правила регистрации и конфиденциальности', '//www.vedomosti.ru/info/privacy', :target => "_blank"

  button{type='submit' ng-disabled='!rules'} Зарегистрироваться

app/views/register/email_form.html.slim
- if @success
  - message = capture
    h5 Проверьте вашу почту
    p На указанный вами адрес электронной почты отправлено письмо. Для восстановления пароля, пройдите по ссылке в письме и введите новый пароль. Убедитесь, что письмо не попало в спам.
    p
      | С уважением,
      br
      | «Ведомости» +7 (495) 232-17-53

  = render 'alert', kind: :success, message: message
- else
  .id-form.id-form__mini
    .row
      .col-md-12
        h5 Восстановление пароля
        .message Укажите вашу почту и мы отправим вам ссылку для сброса пароля.
        = form_for(@email_form, url: password_reset_email_send_path, html: { form: :form, 'ng-submit' => 'submit($event)' }) do |f|
          = f.text_field :email, placeholder: 'E-mail', 'ng-model' => 'email_form.email'
          - if @email_form.errors[:email].present?
            .error = @email_form.errors[:email].first
          .actions
            button{type='submit'} Отправить

app/views/register/oauth_callback.html.slim
= render 'oauth_form'

app/views/register/password_form.html.slim
- if @check_token_success
  - if @success

    - message = capture
      h5 Пароль успешно обновлён.

    = render 'alert', kind: :success, message: message

  - else
    .id-form.id-form__mini
      .row
        .col-md-12
          h5 Восстановление пароля
          .message Ваш пароль будет обновлен.

          = form_for @password_form, url: password_send_path do |f|
            .password-field {password-field='reset-reveal'}
              = f.password_field :password, placeholder: 'Пароль'
              - if @password_form.errors[:password].present?
                .error= @password_form.errors[:password].first
              #reset-reveal.password-field__reveal

            .actions
              button{type='submit'} Отправить

- else
  - message = capture
    h5 Неправильный токен сброса пароля.

  = render 'alert', kind: :error, message: message

app/views/register/sign_up_form.html.slim
.id-form
  .row
    .col-md-5
      div.b-form-divider
      - if !defined?(hide_social_auth)
        .b-subscription-form-fieldset.b-subscription-form-fieldset_right
          = render 'register/oauth_links'

    .col-md-7.dotted
      .wrap
        h5 Регистрация
        = render 'register/password_form', hide_nickname: defined?(hide_nickname) ? hide_nickname : false

app/views/register/social_account_link_failed.html.slim
- message = capture
  h5 Неверная или устаревшая ссылка привязки&nbsp;аккаунта
  p По всем вопросам связанным с авторизацией обращайтесь:<br/>+7 (495) 232 17 53, <a href="mailto:podpiska@vedomosti.ru">podpiska@vedomosti.ru</a><br/>или через <a href="#{Settings.hosts.shark}/info/feedback">форму обратной связи</a>.

= render 'alert', kind: :error, message: message

app/views/register/social_account_link_success.html.slim
- message = capture
  h5 Ваш аккаунт соцсети успешно связан с&nbsp;аккаунтом&nbsp;Ведомостей
  p Теперь вы сможете заходить на сайт и по паролю, и через кнопки соцсетей.
  
= render 'alert', kind: :success, message: message